### ISSUE TITLE
LDN Inboxes for GND entities

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#1]
To notify about corrections, backlinks or else we need an LDN inbox for every GND entity.

Eventually, the inbox URLs (however they will look like) will be added to lobid-gnd (not part of this issue), e.g.:

```json
{
   "@context":"http://lobid.org/gnd/context.jsonld",
   "id":"http://d-nb.info/gnd/4219521-4",
   "inbox":"https://skohub.io/lobid-gnd?id=4219521-4"
}
```

**Comment by literarymachine** [comment]
> the inbox URLs (however they will look like)

My first impulse was to simply go for

`/inbox?target=https://lobid.org/gnd/118696432`

but maybe it makes sense to provide one inbox per user / target as in

`/lobid-gnd/inbox?target=https://lobid.org/gnd/118696432`

Also, how do we validate `target` URIs? Do we provide inboxes for arbitrary URIs? We could somehow couple this to vocabs published using https://github.com/hbz/skohub-ssg, but this is not feasible e.g. for lobid-gnd which will not be published using the static site generator / hosted on skohub.io.
