### ISSUE TITLE
Enable WebSub subscriptions to inboxes

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#2]
Depends on #1.

Clients should be able to subscribe to inboxes so that they get push messages directly after a new notifications arrives.

**Comment by literarymachine** [comment]
To clarify, we will implement two subscription protocols: [WebSub](https://www.w3.org/TR/websub/) (this issue) and [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) (see #5).

**Comment by acka47** [comment]
Reopening as this is not implemented as required in the issue: Subscriptions are currently made directly to the concept and not at its inbox. (Although I already was quite clear in the issue text, I did not review accordingly.)

As people are subscribing to notifications for a concept/resource and not to changes to the resource itself, the Websub subscriptions should be made to the inbox. This means, that we move the LINK headers for websub from the concept (for example GND entry) to its LDN inbox URL.

**Comment by acka47** [comment]
Closing.
