### ISSUE TITLE
Add content as HTML to announce note

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#21]
The structured data from the notification sent to the inbox should be added as HTML snippet (including thumbnail etc.) to the announce note so that apps can easily present it

**Comment by acka47** [comment]
The data should be added in the `content` field. It looks like currently the content from `description` is also put into `content` and it already works good with mastodon, see e.g. https://test.skohub.io/m/bed8d41c-f129-4c1b-aeb3-3d0d2b45104c

**Comment by acka47** [comment]
I am not sure how to best show an image of a resource, though. Will think about this tomorrow.

**Comment by literarymachine** [comment]
For now, we will use `<p>${title}: ${url}</p>`

**Comment by literarymachine** [comment]
On test, see e.g. https://test.skohub.io/m/0322ef82-e268-4c0b-b23d-4b2f8864c395

![image](https://user-images.githubusercontent.com/149825/69334461-098cc880-0c5b-11ea-9dc8-74d4d29c8805.png)

**Comment by acka47** [comment]
+1 Looks good.
