### ISSUE TITLE
Add database persistance

### ISSUE THREAD

**Issue by literarymachine** [hbz/skohub-pubsub#22]
Follower lists and notifications should be stored e.g. in MongoDB.

**Comment by literarymachine** [comment]
Deployed to test, functionality can be verified by:

 - Following https://test.skohub.io/literarymachine/hochschulfaechersystematik/tags/v2.0/w3id.org/class/hochschulfaechersystematik/n1 on Mastodon
- Sending an update to that topic using cURL: `curl 'https://test.skohub.io/inbox?actor=literarymachine/hochschulfaechersystematik/tags/v2.0/w3id.org/class/hochschulfaechersystematik/n1' -H 'Content-Type: application/ld+json' -H 'Accept: application/json' --data-binary $'{"name":"How to use MongoDB with Node.js","id":"https://flaviocopes.com/node-mongodb/","description":"In this tutorial I\'ll show you how to interact with a MongoDB database from Node.js","author":"Flavio Copes","image":"https://flaviocopes.com/img/avatar.png","type":"CreativeWork"}'`
- Verifying the update is received in Mastodon
- Unfollowing https://test.skohub.io/literarymachine/hochschulfaechersystematik/tags/v2.0/w3id.org/class/hochschulfaechersystematik/n1 on Mastodon
- Sending another update as described above
- Verifying no update is received in Mastodon

**Comment by acka47** [comment]
> - Verifying the update is received in Mastodon

I am following https://test.skohub.io/literarymachine/hochschulfaechersystematik/tags/v2.0/w3id.org/class/hochschulfaechersystematik/n1, see https://openbiblio.social/users/acka47/following but don't get any updates when publishing to the inbox. I can see my publications in the inbox, though, see https://test.skohub.io/inbox?actor=literarymachine%2Fhochschulfaechersystematik%2Ftags%2Fv2.0%2Fw3id.org%2Fclass%2Fhochschulfaechersystematik%2Fn1.

**Comment by literarymachine** [comment]
> I am following https://test.skohub.io/literarymachine/hochschulfaechersystematik/tags/v2.0/w3id.org/class/hochschulfaechersystematik/n1

Interesting, I cannot confirm that:

https://test.skohub.io/followers?subject=literarymachine%2Fhochschulfaechersystematik%2Ftags%2Fv2.0%2Fw3id.org%2Fclass%2Fhochschulfaechersystematik%2Fn1

Since I was unsure if there is a problem with new followers, I created another mastodon account. I was able to follow the above subjects and I do get updates:

![image](https://user-images.githubusercontent.com/149825/72259685-582e6180-3611-11ea-9db4-c1551bc27179.png)

I am assuming something went wrong with you following the topic, but I don't know what that could be yet.

**Comment by dr0i** [comment]
It's working for me.

**Comment by dr0i** [comment]
I also can see me at https://test.skohub.io/followers?subject=literarymachine%2Fhochschulfaechersystematik%2Ftags%2Fv2.0%2Fw3id.org%2Fclass%2Fhochschulfaechersystematik%2Fn1 I just see 3 followers: `literarymachine`, `skohub` and `dr0i`. To be listed there seems to be mandatory to push notes to mastodon.

**Comment by acka47** [comment]
It's working for me as well. I must have followed and directly unfollowed or so. Thus, +1 from the functional side.
