### ISSUE TITLE
Discuss possible use cases for SkoHub in MoodleNet

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#24]
Every now and then we had contact with the MoodleNet project as there is lots of overlap in our work (especially with regard to metadata & classification, decentralisation and ActivityPub). I have the feeling that it would make lots of sense to introduce SkoHub-based classifications as actors in MoodleNet to allow for topic-based subscription to relevant educational resources.

We should probably arrange a call, maybe in February. @dajbelshaw & @mayel, what do you think about it?

**Comment by dajbelshaw** [comment]
Yes, let's hash it out here first and then have a call :+1:

**Comment by acka47** [comment]
As far as we understand is MoodleNet about connecting the great number of Moodle instances in use with the goal to foster sharing of learning resources between educators. A general challenge with the federated approach is that users with similar interests might not easily find each other across instances. A SkoHub could be an easy solution to facilitate discovery of relevant content and users.

The general idea is that users tag their content using a classification such as [Educational Subjects Classification](https://w3id.org/class/esc/scheme). Classifications are hosted on a dedicated ActivityPub server (a SkoHub). Each topic also is an ActivityPub actor on this server, providing an [inbox](https://skohub.io/inbox?actor=hbz%2Fvocabs-edu%2Fheads%2Fmaster%2Fw3id.org%2Fclass%2Fesc%2Fn06) and the possibility to be followed. This enables people to connect across instances by following and posting to shared topics.

The process could roughly work like this:

- Alice posts a new resource to the MoodleNet instance of her university
- She mentions [Information and Communication Technologies (ICTs)](https://w3id.org/class/esc/n06
) in the description of her resource
- Bob uses the MoodleNet instance of his university which might not yet be connected with Alice's instance and he is following `ICT` on the SkoHub
- He is thus notified, discovering Alice and the content she shared

(P.S.: We are not familiar with MoodleNet collections or communities and how they already address this. Would it be possible provide us with an account on a test instance?)

**Comment by acka47** [comment]
As the whole MoodleNet team left and, thus, no one with ActivityPub knowledge is left and the future of MoodleNet is unclear, I am closing this issue.
