### ISSUE TITLE
Is webfinger working correctly?

### ISSUE THREAD

**Issue by cKlee** [hbz/skohub-pubsub#27]
If I understood this right, then

[https://skohub.io/.well-known/webfinger?resource=acct:dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/class/hochschulfaechersystematik/n7@skohub.io](https://skohub.io/.well-known/webfinger?resource=acct:dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/class/hochschulfaechersystematik/n7@skohub.io)

should result in

```
href: "https://skohub.io/dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/class/hochschulfaechersystematik/n7"
```

As of https://github.com/hbz/skohub-pubsub/blob/master/src/activitypub.js#L61-L75

Right?

**Comment by literarymachine** [comment]
The webfinger username has to be [hex encoded](https://skohub.io/.well-known/webfinger?resource=acct:68627a2f766f636162732d6564752f68656164732f6d61737465722f773369642e6f72672f636c6173732f6573632f6e3030@skohub.io). We found no other way around the limitation that webfinger usernames cannot contain slashes.

**Comment by cKlee** [comment]
Thanks, Felix!
