### ISSUE TITLE
Discovery via Mastodon does not work

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#35]
Reported by @raphlap via Mastodon DM.

E.g. looking up and following a subject on Mastodon like [shown in the SWIB19 presentation](https://pad.gwdg.de/p/BJvl5sFiB#/13/5) does not work. Is there something wrong with the webfinger setup?

**Comment by acka47** [comment]
Webfinger lookup seems to work, here is how to do it:

1. Get the hex-encoded `preferredUsername` from https://skohub.io/hbz/vocabs-edu/heads/master/w3id.org/class/esc/n06.jsonas (The `.jsonas` document contains the ActivityStreams description of a concept as ActivityPub actor)
2. Lookup the resource like this: https://skohub.io/.well-known/webfinger?resource=acct:2f68627a2f766f636162732d6564752f68656164732f6d6173746572773369642e6f72672f636c6173732f6573632f6e3036@skohub.io

A result comes back there but I can see an error in the `href` URL which looks like this: `https://skohub.io//hbz/vocabs-edu/heads/masterw3id.org/class/esc/n06`. There is one slash too many after `.io` and a slash missing after `/master`. I guess this is the reason for our problem.

**Comment by acka47** [comment]
The code that creates this link is here, I think:

https://github.com/hbz/skohub-pubsub/blob/aeb6ba5911605268b4a3b54073ddbdbee192fbe6/src/activitypub.js#L70

**Comment by literarymachine** [comment]
The error is already in the hex encoded user name, the slash after `master` is already missing here:

> Buffer.from("2f68627a2f766f636162732d6564752f68656164732f6d6173746572773369642e6f72672f636c6173732f6573632f6e3036", "hex").toString()
'/hbz/vocabs-edu/heads/masterw3id.org/class/esc/n06'

Also, the additional slash is already present in the hex string. The `.jsonas` document containing that string is generated here: https://github.com/hbz/skohub-vocabs/blob/master/gatsby-node.js#L113

**Comment by dr0i** [comment]
Tried many things:
- apache configs come to the mind first, but couldn't come up with anything
- not able to debug test-server because of https://github.com/hbz/skohub-vocabs/issues/82 et al.
- Fiddled a bit with `ACTOR=https://skohub.io{+path}` from the `.env` but think it cannot be solved by it.

Lost, atm.

**Comment by dr0i** [comment]
Issue is fixed. @raphlap give it another try!

**Comment by dr0i** [comment]
I reopen this issue because all other vocabs must we build again to be fixed. See a list at https://github.com/hbz/skohub.io/issues/10 .

**Comment by dr0i** [comment]
- [x] https://github.com/dini-ag-kim/hochschulfaechersystematik (already built on skohub.lobid.org) -> https://w3id.org/kim/hochschulfaechersystematik/scheme
- [x] https://github.com/dini-ag-kim/hcrt
- [x] https://github.com/hbz/vocabs-edu

Furthermore:

- [x] https://github.com/acka47/lrmi-resource-types
- [x] https://github.com/acka47/lrmi-audience-role
- [x] https://github.com/literarymachine/skos/ (the license vocab is used in https://github.com/dini-ag-kim/lrmi-profile/blob/20b66f848e93096f48c8457e7ba7331cad0ad3b4/draft/schemas/schema.json#L139, it could also be published elsewhere (KIM?) and the schema be adjusted accordingly, **edit**: I moved it to one of my repos, see https://skohub.io/acka47/license-vocab/heads/master/oerworldmap.org/assets/json/licenses.json.html and updated the schema)

**Comment by acka47** [comment]
Closing
