### ISSUE TITLE
Error when trying to publish to inbox from SkoHub Editor

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#36]
I tried to publish to https://w3id.org/kim/hochschulfaechersystematik/n06. [edit dr0i: e.g go to my webblog, use the browser-extension to open the skohub-editor, add a subject there (mandatory!) and click on the `publish` button at the end]. This is what I get.

![image](https://user-images.githubusercontent.com/160292/85015304-0bbef300-b168-11ea-9988-844916e3a05b.png)

The browser console gives:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://test.skohub.io/inbox?actor=dini-ag-kim/hochschulfaec…tik/heads/master/w3id.org/kim/hochschulfaechersystematik/n06. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by acka47** [comment]
Apparently, the problem is that CORS headers are not set for the test instance. Thus, there are two possible solutions:

1. Set CORS headers for test.skohub.io
2. Publish to production (skohub.io). Here is the code that would have to be adjusted (I think): 
https://github.com/hbz/skohub-editor/blob/50932dd489b540377ea3a97a4acb44d57a463754/src/components/JSONPointerForm/SkohubLookup.js#L71-L81

**Comment by acka47** [comment]
@literarymachine I forgot the reason why SkoHub Editor publishes to the test server. Does this still make sense?

**Comment by literarymachine** [comment]
> Thus, there are two possible solutions

We should probably do both and have concepts from skohub.io publish to the production inbox and concepts from test.skohub.io publish to the test inbox.

**Comment by acka47** [comment]
@dr0i Please set the CORS header for test and we will also publish to production from the production editor (& the extension).

**Comment by dr0i** [comment]
Deployed to test and production, closed.
